services:
  app:
    container_name: app
    build: .
    restart: always
    links:
      - mongo
    volumes: 
      - ./combined.log:/usr/src/app/combined.log
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes: 
      - mongodata:/data/db
volumes:
  mongodata:
